-- Profile definitions for SellIt
local profiles = {
    -- Crystals profile - sells all basic elemental crystals
    ['crystals'] = {
        'fire crystal',
        'water crystal',
        'earth crystal',
        'wind crystal',
        'ice crystal',
        'lightning crystal',
        'light crystal',
        'dark crystal'
    },

    -- Basic ore profile - common mining materials
    ['ore'] = {
        'iron ore',
        'copper ore',
        'zinc ore',
        'silver ore',
        'mythril ore'
    },

    -- Fish profile - common fish to sell
    ['fish'] = {
        'forest carp',
        'bastore sardine',
        'cobalt jellyfish'
    },

    -- Junk profile - common items you might want to sell
    ['junk'] = {
        'little worm',
        'bone chip',
        'shell bug',
        'bird feather',
        'insect wing',
        'bat wing',
        'fire crystal',
        'water crystal',
        'earth crystal',
        'wind crystal',
        'ice crystal',
        'lightning crystal',
        'light crystal',
        'dark crystal',
        'snow geode',
        'fire geode',
        'water geode',
        'earth geode',
        'wind geode',
        'ice geode',
        'lightning geode',
        'shadow geode',
        'ifritite',
        'shivite',
        'garudite',
        'ramuite',
        'carbite',
        'leviatite',
        'platinum silk',
        'Twill damask',
        'Kejusu Satin',
        'Siren\'s Hair',
        'Ram Horn',
        'Coral Fragment',
        'Behem. Leather',
        'Ram Skin',
        'Chrysoberyl',
        'Painite',
        'Potion', 
        'Gugru Tuna', 
        'Cobalt Jellyfish', 
        'Shall Shell', 
        'Dragon Fruit', 
        'Gigant Squid', 
        'Bluetail', 
        'Mackerel', 
        'Moorish Idol', 
        'Grimmonite', 
        'Kukuru Bean', 
        'Puffball', 
        'Sunflower Seeds', 
        'Poison Flour', 
        'Blue Peas', 
        'Kopparnickel Ore', 
        'Pugil Scales', 
        'Uragnite Shell', 
        'Dragon Bone', 
        'Turtle Shell', 
        'Swamp Ore', 
        'Fish Bones', 
        'Aht Urhgan Brass', 
        'Iron Ore', 
        'Gold Ore', 
        'Pebble', 
        'Platinum Ore', 
        'H.Q. Scp. Shell', 
        'Meteorite', 
        'Phrygian Ore', 
        'Zinc Ore', 
        'Elshimo Newt', 
        'Moat Carp', 
        'Copper Frog', 
        'Gavial Fish', 
        'Crescent Fish', 
        'Giant Catfish', 
        'Ca Cuong', 
        'Yorchete', 
        'Pamamas', 
        'Walnut', 
        'Guatambu Log', 
        'Chestnut Log', 
        'Arrowwood Log', 
        'Maple Log', 
        'Grove Cuttings', 
        'Walnut Log', 
        'Elm Log', 
        'Urunday Log', 
        'Dogwood Log', 
        'Mahogany Log', 
        'Felicifruit', 
        'King Locust', 
        'Yagudo Cherry', 
        'Persikos', 
        'Divine Log', 
        'Oak Log', 
        'El. Pachira Fruit', 
        'Flax Flower', 
        'Skull Locust', 
        'Wijnruit', 
        'Red Rose', 
        'Watermelon', 
        'Red Moko Grass', 
        'Dark Bass', 
        'Gold Carp', 
        'Black Eel', 
        'Igneous Rock', 
        'Snapping Mole', 
        'Darksteel Ore', 
        'Khroma Ore', 
        'Tin Ore', 
        'Scorpion Shell', 
        'H.Q. Crab Shell', 
        'Scorpion Claw', 
        'Marguerite', 
        'Ulbukan Lobster', 
        'Yayinbaligi', 
        'Pipira', 
        'Ruddy Seema', 
        'Eggplant', 
        'Saruta Cotton', 
        'Ulbuconut', 
        'Antlion Jaw', 
        'Auric Sand', 
        'Dst. Nugget', 
        'Orichalcum Ore', 
        'Vanadium Ore', 
        'Voay Staff -1', 
        'Contortopus', 
        'Adoulinian Kelp', 
        'Black Prawn', 
        'Dragon Talon', 
        'Beetle Jaw', 
        'Crab Shell', 
        'Brass Loach', 
        'Rusty Bucket', 
        'Tree Cuttings', 
        'Ash Log', 
        'Spider Web', 
        'Fresh Marjoram', 
        'Yagudo Drink', 
        'Three-eyed Fish', 
        'Cone Calamary', 
        'Zebra Eel', 
        'Quus', 
        'Bastore Bream', 
        'Titanictus', 
        'Rye Flour', 
        'Adaman Ore', 
        'Crayfish', 
        'Lacquer Tree Log', 
        'Rolanberry', 
        'Napa', 
        'Lesser Chigoe', 
        'Bloodblotch', 
        'Bat Fang', 
        'Ebony Log', 
        'Fresh Mugwort', 
        'Pine Nuts', 
        'Crawler Cocoon', 
        'Acorn', 
        'Black Ghost', 
        'Faerie Apple', 
        'Red Terrapin', 
        'Barnacle', 
        'Vegetable Seeds', 
        'Chestnut', 
        'Coral Fungus', 
        'Bhefhel Marlin', 
        'Dwarf Remora', 
        'Win. Tea Leaves', 
        'Sheep Tooth', 
        'Blk. Tiger Fang', 
        'Wootz Ore', 
        'Bugard Tusk', 
        'Loc. Elutriator', 
        'Senroh Sardine', 
        'Silver Ore', 
        'Green Rock', 
        'Giant Stinger', 
        'Burdock', 
        'La Theine Cbg.', 
        'Grain Seeds', 
        'Pumpkin Pie', 
        'Nopales', 
        'San d\'Or. Flour', 
        'Dryad Root', 
        'Crawler Egg', 
        'Semolina', 
        'Tiny Goldfish', 
        'Woozyshroom', 
        'Matsya', 
        'Dragonfish', 
        'Flint Stone', 
        'Velkk Necklace', 
        'Velkk Mask', 
        'Matamata Shell', 
        'Titanium Ore', 
        'Moko Grass', 
        'Emperor Fish', 
        'Isleracea', 
        'Cactus Stems', 
        'Wivre Maul',
        'Raptor Skin',
        'Peiste Skin',
        'Slime Juice',
        'Infinity Core',
        'Acheron Shield',
        'Hare Meat',
        'Honey',
        'Land Crab Meat',
        'Bird Egg',
        'Rabbit Hide',
        'Beehive Chip',
        'Flytrap Leaf',
        'Colibri Beak',
        'Chapuli Horn',
        'Craklaw Pincer',
        'Chapuli Wing',
        'Snap. Tendril',
        'Raaz Hide',
        'Raaz Tusk',
        'Snap. Secretion',
        'Orobon Lure',
        'Orobon Meat',
        '2Leaf Mandra Bud',
        'Shadow Geode',
        'Garudite',
        'Fenrite',
        'Doll Shard',
        'Leviatite',
        'Airlixir',
        'Airlixir +1',
        'Twinthread',
        'Cerberus Meat',
        'Mind Potion',
        'Dragon Meat',
        'Kitron',
        'King Truffle',
        'Pebble',
        'Tin Ore',
        'Darksteel Ore',
        'Khroma Ore',
        'Orichalcum Ore',
        'Vanadium Ore',
        'Mythril Ore',
        'Steel Ingot',
        'Mythril Ingot',
        'Darksteel Ingot',
        'Khroma Ingot',
        'Damascus Ingot',
        'Ocl. Sheet',
        'Hi-Potion',
        'Hi-Potion +1',
        'Hi-Potion +2',
        'Hi-Potion +3',
        'X-Potion',
        'X-Potion +1',
        'X-Potion +2',
        'X-Potion +3',
        'Elixir',
        'Elixir +1',
        'Elixir +2',
        'Elixir +3',
        'Pro-Ether',
        'Pro-Ether +1',
        'Pro-Ether +2',
        'Pro-Ether +3',
        'Ether',
        'Ether +1',
        'Ether +2',
        'Ether +3',
        'Beech Log',
        'Petrified Log',
        'Gold Ingot',
        'Platinum Ingot',
        'Durium Ore',
        'Red Rock',
        'Purple Rock',
        'Aquamarine',
        'Wyvern Scales',
        'Demon Horn',
        'Phil. Stone',
        'Teak Log',
        'Jacaranda Log',
        'Eudaemon Sash',
        'Moonstone',
        'Wyvern Skin',
        'Raxa',
        'Temper',
        'Yurin: Ichi',
        'Gain-MND',
        'Durium Sheet',
        'Yellow Rock',
        'Sunstone',
        'Zircon',
        'Gold Thread',
        'Manticore Hide',
        'Flocon-de-mer',
        'Titanite',
        'Hi-Elixir',
        'Icarus Wing',
        'Stone V',
        'Blizzaja',
        'Waterja',
        'Aeroja',
        'Stoneja',
        'Firaja',
        'Thundaja',
        'Earth Carol II',
        'Gain-VIT',
        'Gain-AGI',
        'Gain-INT',
        'Gain-CHR',
        'Gain-DEX',
        'Gain-STR',
        'Black Rock',
        'Jadeite',
        'Fluorite',
        'Silk Thread',
        'Wyvern Tailskin',
        'Flame Geode',
        'Faithful Legs I',
        'Warthog Meat',
        'White Rock',
        'G. Bird Plume',
        'G. Bird Feather',
        'Seashell',
        'Bomb Ash',
        'Iron Sand',
        'Breeze Geode',
        'Thunder Geode',
        'Light Geode',
        'Sulfur',
        'Revival Root',
        'Puk Egg',
        'Tiger Hide',
        'Puk Wing',
        'Chimera Blood',
        'Cermet Chunk',
        'Bismuth Ore',
        'Beryllium Ore',
        'Maculele Earring',
        'Translucent Rock',
        'Imp Wing',
        'Fiendish Skin',
        'Anc. Beast Horn',
        'Aqua Geode',
        'Eudaemon Ring',
        'Ziz Meat',
        'Giant Bird Fthr.',
        'Fiend Blood',
        'Lizard Tail',
        'Endark',
        'Ruszor Meat',
        'Brass Ingot',
        'Hydra Fang',
        'Prize Powder',
        'Indi-Malaise',
        'Crawler Cocoon',
        'Red Moko Grass',
        'Mushrm. Locust',
        'Heathen\'s Earring',
        'Lizard Egg',
        'Sentinel\'s Scherzo',
        'Tigerhunter',
        'Erebus\'s Lance',
        'Chiner\'s Belt',
        'Tableware Set',
        'Steam Clock',
        'Bloodwood Log',
        'Lizard Skin',
        'Bugard Skin',
        'Peiste Stinger',
        'Curaga V',
        'Animus Augeo',
        'Scopuli Nails',
        'Slime Oil',
        'Dhalmel Hide',
        'Flan Meat',
        'Ameretat Vine',
        'Smilodon Hide',
        'Ice Cluster',
        'Scream Fungus',
        'Phalanx',
        'Flare',
        'Freeze',
        'Quake',
        'Flood',
        'Aera II',
        'Utsusemi: Ni',
        'Utsusemi: Ichi',
        'Myoshu: Ichi',
        'Hydra Meat',
        'Sardonyx',
        'Soiled Letter',
        'Vivio Crab Shell',
        'Fire Fewell',
        'Ice Fewell',
        'Soil Geode',
        'Faithful Legs II',
        'Faithful Legs III',
        'Raise III',
        'Tornado',
        'Burst',
        'Stonera II',
        'Thundara II',
        'Indi-Gravity',
        'Humus',
        'Vivified Coral',
        'Vivio Femur',
        'Faithful\'s Torso I',
        'Faithful\'s Torso II',
        'Faithfl. Torso III',
        'Faithful\'s Legs III',
        'Saffron Blossom',
        'Midrium Ore',
        'Gold. Kit 45',
        'Cure VI',
        'Cure V',
        'Cure IV',
        'Blizzara II',
        'Agaricus',
        'Olympus Sash',
        'Lm. Rm. Leather',
        'Laceratrice',
        'Verboshroom',
        'Kakka: Ichi',
        'Kakka: Ni',
        'Lithic W. Scale',
        'Belladonna Sap',
        'W. Spider\'s Web',
        'Refresh II',
        'Indi-Frailty',
        'Indi-Barrier',
        'Indi-Refresh',
        'Indi-Fade',
        'Taurus Horn',
        'Smth. Btl. Jaw',
        'Cirdas Visage III',
        'Mahogany Lbr.',
        'Boyahda Moss',
        'Beastman Blood',
        'Copper Ore',
        'Ra\'Ka. Visage I',
        'Ra\'Ka. Visage II',
        'Ra\'Ka. Visage III',
        'Dark Cluster',
        'Apple Juice',
        'Snoll Arm',
        'Avatar Blood',
        'Lizard Blood',
        'Bronze Bullet',
        'Coeurl Meat',
        'Istiridye',
        'Sharug Greens',
        'Vomp Carrot',
        'Zegham Carrot',
        'Adaman Ingot',
        'Bamboo Stick',
        'Gold Chain',
        'Grass Thread',
        'Cotton Cloth',
        'Undead Skin',
        'Coeurl Hide',
        'Lamp Marimo',
        'Void Crystal',
        'Void Grass',
        'Rolanberry Pie',
        'Cotton Cloth',
        'Rusty Subligar',
        'Rusty Leggings',
        'Wyvern Wing',
        'Indi-Haste',
        'Amber',
        'Titanite',
        'Ramuite',
        '??? Earring: RDM',
        '??? Earring: WHM',
        '??? Earring: BLM',
        '??? Earring: SMN',
        '??? Earring: SCH',
        '??? Earring: GEO',
        '??? Earring: RUN',
        '??? Earring: COR',
        '??? Earring: DNC',
        '??? Earring: BRD',
        '??? Earring: PUP',
        '??? Earring: NIN',
        '??? Earring: PLD',
        '??? Earring: WAR',
        '??? Earring: DRK',
        '??? Earring: MNK',
        '??? Earring: SAM',
        '??? Earring: DRG',
        '??? Earring: BLU',
        '??? Earring: RNG',
        '??? Earring: THF',
        '??? Earring: BST',
        'Deathball',
        'Kazham Peppers',
        'Tarutaru Rice',
        'Black Pepper',
        'Demon Skull',
        'Karakul Skin',
        'Mohbwa Cloth',
        'Scintillant Ingot',
        'Soulfl. Tentacle',
        'Almond',
        'Faithful\'s Torso IV',
        'Faithful\'s Legs IV',
        'Faithful\'s Legs I',
        'Faithful\'s Legs II',
        'Faithful\'s Torso III',
        'Rosewood Log',
        'Mistletoe',
        'Magic Pot Shard',
        'Dragon Blood',
        'Khimaira Horn',
        'Sage',
        'Habaneros',
        'Vanilla',
        10
    }
}

return profiles 