-- Items to automatically drop when they enter inventory
local autodrop = {
    'swiftwing',
    'Idi\'s Mask',
    'Ritualistic Plans',
    'Tutelary Plans',
    'Genta Hera-Ate',
    'Neit\'s Coat',
    'Ice Crest Card',
    'Fire Crest Card',
    'Wind Crest Card',
    'Earth Crest Card',
    'Lightning Crest Card',
    'Water Crest Card',
    'Light Crest Card',
    'Dark Crest Card',
    'Voidtorso: BST',
    'Footshard: RNG',
    'Poroggo Hat',
    'creed seal: lg.',
    'Sanguine Spike',
    'Askar Zucchetto',
    'Caller Seal: Hd.',
    'Cirque Seal: Hd.',
    'G. Seed Pouch',
    'M. Beetle Saliva',
    'Nvrch. Seal: Lg.',
    'Kamome',
    'Springstone',
    'Meridian Ring',
    'Aquiline Belt',
    'Balance Jewel',
    'Balance Card',
    'Balance Stone',
    'Balance Coin',
    'Voyage Jewel',
    'Voyage Stone',
    'Voyage Coin',
    'Voyage Card',
    'Ardor Stone',
    'Ardor Jewel',
    'Ardor Coin',
    'Ardor Card',    
    'Chocobo Wand',
    'Vision Card',
    'Vision Jewel',
    'Vision Stone',
    'Vision Coin',
    'Wieldance Jewel',
    'Wieldance Stone',
    'Wieldance Card',
    'Wieldance Coin',
    '??? Polearm',
    'Tutelary Plans',
    'Ate\'s Sollerets',
    'Namru\'s Dastanas',
    'Soil Sachet',
    'Mageblade',
    'Orc Helmet',
    'Bottled Pixie',
    'Neit\'s Cuffs',
    'Namru\'s Shalwar',
    'Monster Belt',
    'Crobaci',
    'Shadow Sachet',
    'Phuabo Organ',
    'H. Qdv. Chestplate',
    'Punch Bug',
    'M.Abjuration: Ft.',
    '??? Gloves',
    '??? Boots',
    '??? Head',
    '??? Body',
    '??? Legs',
    '??? Hands',
    'A.Abjuration: Hn.',
    'A.Abjuration: Ft.',
    'Soulflayer Robe',
    'Soulflayer Staff',
    'Hero\'s Reflections',
    'Mage\'s Staff',
    'Elder Staff',
    'D.Abjuration: Ft.',
    'M.Abjuration: Lg.',
    'Mannequin Hands',
    'P.Abjuration: Lg.',
    
    -- CAUTION THESE WILL BE DROPPED
};

return autodrop; 